(draw (change (polygon 6)
              (rotate 1/4)
              (scale 1/9))
      (change (polygon 6)
              (scale     1/2)
              (translate 1)
              (rotate    1/4)
              (rotate    0 1/3 2/3)
              (group (combine (rotate 1)   (scale 1))
                     (combine (rotate 1/2) (scale 2/3)))
              (scale 1/2)))
